data:
  requests_cpu: "0.1"
  requests_memory: "400M"
  limits_cpu: "1"
  limits_memory: "1G"
  bootstrap_limits_cpu: "0.2"
  bootstrap_limits_memory: "200M"
  bootstrap_image: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "schema"
conf:
  app_name: "schema"
  bootstrap_secret_name: "datafier-secret"
  configmap: "schema-config"
  minio_secret_name: "schema-minio-secret"
  on_prem_enabled: false
  postgres_secret_name: "schema-postgres-secret"
  rabbitmq_secret_name: "rabbitmq-secret"
  domain: ""
