variables:
  BUILD_BOOTSTRAP_PATH: "devops/$OSDU_GCP_VENDOR/bootstrap-osdu-module/Dockerfile"
  OSDU_GCP_ENABLE_BOOTSTRAP: "true"
  OSDU_GCP_SERVICE: schema
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_HELM_TIMEOUT: "--timeout 15m"

osdu-gcp-test:
  variables:
    OSDU_GCP_TEST_SUBDIR: testing/schema-test-core
  script:
    - $MAVEN_BUILD . test-results.log verify -q -f $OSDU_GCP_TEST_SUBDIR/pom.xml

osdu-gcp-dev2-test:
  variables:
    OSDU_GCP_TEST_SUBDIR: testing/schema-test-core
  script:
    - $MAVEN_BUILD . test-results.log verify -q -f $OSDU_GCP_TEST_SUBDIR/pom.xml

osdu-gcp-anthos-test:
  variables:
    OSDU_GCP_TEST_SUBDIR: testing/schema-test-core
  script:
    - $MAVEN_BUILD . test-results.log verify -q -f $OSDU_GCP_TEST_SUBDIR/pom.xml
