parameters:
  environments: []
  serviceName: 'schema-service'
  skipTests: 'false'
  skipDeploy: 'false'
  valuesFile: ''
  chartPath: ''

stages:
  - template: /devops/build-stage.yml@TemplateRepo
    parameters:
      mavenGoal: 'package'
      mavenPublishJUnitResults: true
      serviceCoreMavenOptions: '--projects schema-core -Dmaven.test.skip=true'
      mavenOptions: '--projects provider/schema-azure -Dmaven.test.skip=true'
      copyFileContents: |
        pom.xml
        provider/schema-azure/maven/settings.xml
        provider/schema-azure/pom.xml
        provider/schema-azure/target/*-spring-boot.jar
      copyFileContentsToFlatten: ''
      mavenSettingsFile: './maven/settings.xml'
      serviceBase: ${{ parameters.serviceName }}
      testingRootFolder: 'testing'
      chartPath: ${{ parameters.chartPath }}

  # Deploy for each environment
  - ${{ each environment in parameters.environments }}:  

      - template: /devops/deploy-stages.yml@TemplateRepo
        parameters:
          serviceName: ${{ parameters.serviceName }}
          chartPath: ${{ parameters.chartPath }}
          valuesFile: ${{ parameters.valuesFile }}
          skipDeploy: ${{ parameters.skipDeploy }}
          skipTest: ${{ parameters.skipTests }}
          providers:
            -  name: Azure
               environments:
               - ${{ environment.name }}
                     
      - template: bootstrap.yml
        parameters:
          providers:
          - name: Azure
            environments:
            - ${{ environment.name }}