variables:
  GCP_BUILD_SUBDIR: provider/schema-gcp
  GCP_INT_TEST_SUBDIR: testing/schema-test-gcp
  GCP_APPLICATION_NAME: os-schema
  GCP_ENVIRONMENT: dev
  GCP_PROJECT: opendes
  GCP_TENANT_NAME: opendes
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com
  GCP_STORAGE_URL: https://os-schema-dot-opendes.appspot.com/api/storage/v2/

include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'service.gitlab-ci.yml'
