variables:
  GCP_BUILD_SUBDIR: provider/schema-gcp
  GCP_INT_TEST_SUBDIR: testing/schema-test-gcp
  GCP_APPLICATION_NAME: os-schema
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com

  IBM_BUILD_SUBDIR: provider/schema-ibm
  IBM_INT_TEST_SUBDIR: testing/schema-test-core
  IBM_TEST_CMD: verify
  IBM_DEPLOYMENTS_SUBDIR: deployments/scripts/ibm
  IBM_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts

  AZURE_SERVICE: schema
  AZURE_BUILD_SUBDIR: provider/schema-azure
  AZURE_TEST_SUBDIR: testing/schema-test-core
  AZURE_ONLY_TEST_SUBDIR: testing/schema-test-azure
  AZURE_DEPLOYMENTS_SUBDIR: deployments/scripts/azure
  AZURE_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts
  AZURE_CLIENT_ID: $AZURE_PRINCIPAL_ID
  AZURE_CLIENT_SECRET: $AZURE_PRINCIPAL_SECRET
  DATA_PARTITION: opendes
  AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=${AZURE_BASE}data;AccountKey=${AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net

  AWS_BUILD_SUBDIR: provider/schema-aws/build-aws
  AWS_TEST_SUBDIR: testing/schema-test-core
  AWS_DEPLOYMENTS_SUBDIR: deployments/scripts/aws
  AWS_SERVICE: schema
  AWS_ENVIRONMENT: dev
  AWS_MAVEN_TEST_COMMAND_OVERRIDE: verify
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-schema

  OSDU_GCP_SERVICE: schema
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_TESTS_SUBDIR: testing/schema-test-core
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_DEPLOYMENTS_SUBDIR: deployments/scripts/google
  OSDU_GCP_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts
  OSDU_GCP_HELM_CONFIG_SERVICE: schema-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: schema-deploy
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.log_level=INFO  --set data.authorize_api=$OSDU_GCP_AUTHORIZE_API --set data.google_audiences=$GOOGLE_AUDIENCE --set data.partition_api=$OSDU_GCP_PARTITION_API --set data.shared_tenant_name=$OSDU_GCP_TENANT"
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA  --set data.serviceAccountName=workload-identity-schema"

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

  - local: "/devops/azure/gitlab-bootstrap.yml"
  - local: "/devops/aws/bootstrap.yaml"
  - local: "/devops/ibm/bootstrap.yaml"
  - local: "/devops/gcp/bootstrap.yaml"

osdu-gcp-test:
  image: maven:3.6.3-jdk-8
  script:
    - $MAVEN_BUILD . test-results.log verify -q -f $OSDU_GCP_TESTS_SUBDIR/pom.xml
  artifacts:
    when: always
    paths:
      - test-results.log
      - $OSDU_GCP_TESTS_SUBDIR/target/*/TEST-*.xml
    reports:
      junit:
        - $OSDU_GCP_TESTS_SUBDIR/target/*/TEST-*.xml
