variables:
  GCP_BUILD_SUBDIR: provider/schema-gcp
  GCP_INT_TEST_SUBDIR: testing/schema-test-gcp
  GCP_APPLICATION_NAME: os-schema
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com

  IBM_BUILD_SUBDIR: provider/schema-ibm
  IBM_INT_TEST_SUBDIR: testing/schema-test-core
  IBM_TEST_CMD: verify
  IBM_DEPLOYMENTS_SUBDIR: deployments/scripts/ibm
  IBM_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts

  AZURE_SERVICE: schema
  AZURE_BUILD_SUBDIR: provider/schema-azure
  AZURE_TEST_SUBDIR: testing/schema-test-core
  AZURE_ONLY_TEST_SUBDIR: testing/schema-test-azure
  AZURE_DEPLOYMENTS_SUBDIR: deployments/scripts/azure
  AZURE_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts
  AZURE_CLIENT_ID: $AZURE_PRINCIPAL_ID
  AZURE_CLIENT_SECRET: $AZURE_PRINCIPAL_SECRET
  DATA_PARTITION: opendes
  AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=${AZURE_BASE}data;AccountKey=${AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD

  AWS_BUILD_SUBDIR: provider/schema-aws/build-aws
  AWS_TEST_SUBDIR: testing/schema-test-core
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_DEPLOYMENTS_SUBDIR: deployments/scripts/aws
  AWS_SERVICE: schema
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_MAVEN_TEST_COMMAND_OVERRIDE: verify
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-schema

  MONGODB_AWS_SERVICE: schema
  MONGODB_AWS_BUILD_SUBDIR: provider/schema-aws/build-aws
  MONGODB_AWS_TEST_SUBDIR: testing/schema-test-core
  MONGODB_AWS_EKS_DEPLOYMENT_NAME: os-schema

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-mongodb-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-mongodb-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-java-git.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-global.yml"

  - local: "devops/gcp/pipeline/override-stages.yml"

  - local: "/devops/azure/gitlab-bootstrap.yml"
  - local: "/devops/aws/bootstrap.yaml"
  - local: "/devops/ibm/bootstrap.yaml"
