variables:
  GCP_BUILD_SUBDIR: provider/schema-gc
  GCP_INT_TEST_SUBDIR: testing/schema-test-gc
  GCP_APPLICATION_NAME: os-schema
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com

  IBM_BUILD_SUBDIR: provider/schema-ibm
  IBM_INT_TEST_SUBDIR: testing/schema-test-core
  IBM_TEST_CMD: verify
  IBM_DEPLOYMENTS_SUBDIR: deployments/scripts/ibm
  IBM_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts
  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-schema-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-schema-deploy

  AZURE_SERVICE: schema
  AZURE_BUILD_SUBDIR: provider/schema-azure
  AZURE_TEST_SUBDIR: testing/schema-test-core
  AZURE_ONLY_TEST_SUBDIR: testing/schema-test-azure
  AZURE_DEPLOYMENTS_SUBDIR: deployments/scripts/azure
  AZURE_DEPLOYMENTS_SCRIPTS_SUBDIR: deployments/scripts
  AZURE_CLIENT_ID: $AZURE_PRINCIPAL_ID
  AZURE_CLIENT_SECRET: $AZURE_PRINCIPAL_SECRET
  DATA_PARTITION: opendes
  AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
  AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=${AZURE_BASE}data;AccountKey=${AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD

  AWS_BUILD_SUBDIR: provider/schema-aws/build-aws
  AWS_TEST_SUBDIR: testing/schema-test-core
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_DEPLOYMENTS_SUBDIR: deployments/scripts/aws
  AWS_SERVICE: schema
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_MAVEN_TEST_COMMAND_OVERRIDE: verify
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-schema

  MONGODB_AWS_SERVICE: schema
  MONGODB_AWS_BUILD_SUBDIR: provider/schema-aws/build-aws
  MONGODB_AWS_TEST_SUBDIR: testing/schema-test-core
  MONGODB_AWS_EKS_DEPLOYMENT_NAME: os-schema
  MONGODB_AWS_DEPLOY_TARGET: TF

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  # - project: "osdu/platform/ci-cd-pipelines"
  #   file: "cloud-providers/aws-mongodb-global.yml"

  # - project: "osdu/platform/ci-cd-pipelines"
  #   file: "cloud-providers/aws-mongodb-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-java-git.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/core-global.yml"

  - local: "devops/gc/pipeline/override-stages.yml"
  - local: "devops/core-plus/pipeline/override-stages.yml"

  - local: "/devops/azure/gitlab-bootstrap.yml"
  - local: "/devops/azure/override-stages.yml"

  - local: "/devops/aws/bootstrap.yaml"
  - local: "/devops/ibm/bootstrap.yaml"
  - local: "/publish.yml"

download_plugins:
  image: maven:3.8.3-openjdk-17-slim
  stage: build
  variables:
    OSM_PACKAGE_REGISTRY_URL: "https://community.opengroup.org/api/v4/projects/1448/packages/maven"
    OSM_VERSION: "0.27.3"
    OBM_PACKAGE_REGISTRY_URL: "https://community.opengroup.org/api/v4/projects/1441/packages/maven"
    OBM_VERSION: "0.27.3"
    OQM_PACKAGE_REGISRTY_URL: "https://community.opengroup.org/api/v4/projects/1450/packages/maven"
    OQM_VERSION: "0.27.2"

  artifacts:
    paths:
      - ./tmp/*.jar
    when: always
    expire_in: 1 days

  script:
    - mvn dependency:copy -DrepoUrl=$OSM_PACKAGE_REGISTRY_URL -Dartifact="org.opengroup.osdu:os-osm-postgres:$OSM_VERSION:jar:plugin" -Dtransitive=false -DoutputDirectory="./tmp"
    - mvn dependency:copy -DrepoUrl=$OBM_PACKAGE_REGISTRY_URL -Dartifact="org.opengroup.osdu:os-obm-minio:$OBM_VERSION:jar:plugin" -Dtransitive=false -DoutputDirectory="./tmp"
    - mvn dependency:copy -DrepoUrl=$OQM_PACKAGE_REGISRTY_URL -Dartifact="org.opengroup.osdu:os-oqm-rabbitmq:$OQM_VERSION:jar:plugin" -Dtransitive=false -DoutputDirectory="./tmp"

  only:
    variables:
      - $PROTECTED == '1'

aws-test-java:
  image: $CI_REGISTRY/osdu/platform/deployment-and-operations/base-containers-aws/aws-maven/aws-maven:v2.0

# aws-mongodb-test-java:
#   image: $CI_REGISTRY/osdu/platform/deployment-and-operations/base-containers-aws/aws-maven/aws-maven:v2.0
