global:
  domain: ""
  onPremEnabled: false

data:
  #Configmaps
  dataPartitionId: ""
  entitlementsHost: "http://entitlements"
  javaOptions: "-Xms512M -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45"
  logLevel: "ERROR"
  partitionHost: "http://partition"
  schemaTopicName: "schema-changed"
  schemaChangedMessagingEnabled: true
  springProfilesActive: "gcp"
  datastoreKind: "system_schema_osm"
  datastoreNamespace: "dataecosystem"
  enableCleanup: false
  schemaBucket: ""
  schemaHost: "http://schema"
  #Deployments
  requestsCpu: "5m"
  requestsMemory: "1.6G"
  limitsCpu: "1"
  limitsMemory: "2.5G"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "schema"

conf:
  appName: "schema"
  bootstrapSecretName: "datafier-secret"
  configmap: "schema-config"
  minioSecretName: "schema-minio-secret"
  postgresSecretName: "schema-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "6m"
  bootstrapProxyCPULimit: "100m"
