global:
  domain: ""
  limitsEnabled: true
  dataPartitionId: ""
  logLevel: "ERROR"
  tier: ""
  autoscalingMode: "cpu"

data:
  #Configmaps
  entitlementsHost: "http://entitlements"
  javaOptions: "-Xms512M -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication -XX:InitiatingHeapOccupancyPercent=45"
  logLevel: ""
  partitionHost: "http://partition"
  schemaTopicName: "schema-changed"
  schemaChangedMessagingEnabled: true
  schemaHost: "http://schema"
  #Deployments
  requestsCpu: "220m"
  requestsMemory: "1.7G"
  limitsCpu: "1"
  limitsMemory: "2.5G"
  bootstrapImage: ""
  bootstrapServiceAccountName: ""
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "schema"
  affinityLabelsSpot:
    cloud.google.com/gke-provisioning:
      - spot
  affinityLabelsStandard:
    cloud.google.com/gke-provisioning:
      - standard

conf:
  appName: "schema"
  configmap: "schema-config"

istio:
  proxyCPU: "90m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "10m"
  bootstrapProxyCPULimit: "100m"

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu:
    utilization: 200
    scaleUpStabilizationWindowSeconds: 30
    scaleUpValue: 200
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 150
    scaleDownValue: 100
    scaleDownPeriod: 15
  requests:
    targetType: "AverageValue"
    targetValue: 40
    scaleUpStabilizationWindowSeconds: 10
    scaleUpValue: 50
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 60
    scaleDownValue: 25
    scaleDownPeriod: 60

local_ratelimit:
  max_tokens: 75
  tokens_per_fill: 75
  fill_interval: "1s"
