data:
# common
  javaAppJar: "/deployments/*-spring-boot.jar"
  serverPort: 8080
  contextPath: "/api/schema-service/v1"
  
# log
  logPrefix: schema
  loggingLevelOsdu: debug
  loggingLevelSpring: debug

# ibm 
  beanDefOverriding: true
  healthCheckUri: "/api/schema-service/v1/info"
 
#authorization
  #check cm template
  authorizeAPI: http://TBD:8080/api/entitlements/v2
  deployEnv: CLOUD
  
#db 
  #dbURL-refer-configmap-template
  dbURL: http://tbd:5984
  #get-from-existing secret
  dbUser: admin
  envPrefix: ibm-iks
  #get-from-existing secret  
  dbPassw: tbd

#minio
  accessKey: tbd
  secretKey: tbd

#tenant-validation
  pKCEndPointHost: referenv
  keycloakRealm: OSDU
  pKCClientId: partition-service
  pKCClientSecret: referenv
  grantType: password
  pKCPassword: changeit
  pKCUser: partition-service-admin
  pKAcceptHttp: true
  tenantCacheExpiryInSec: 10000
  #refer-cm-template
  patitionAPI: refer-configmap-template


conf:
  configmap: "schema-config"
