variables:
  CORE_BUILD_BOOTSTRAP_PATH: "devops/core-plus/bootstrap-osdu-module/Dockerfile"
  CORE_BUILD_PATH: "schema-core-plus/cloudbuild/Dockerfile"
  CORE_HELM_PACKAGE_NAME: core-plus-schema-deploy
  CORE_ENABLE_BOOTSTRAP: "true"
  CORE_SERVICE: schema
  CORE_HELM_TIMEOUT: "--timeout 15m"

core-test:
  variables:
    CORE_TEST_SUBDIR: testing/schema-test-core
    HOST: https://osdu.core-dev.gcp.gnrg-osdu.projects.epam.com
    PRIVATE_TENANT1: osdu
    PRIVATE_TENANT2: osdu
    SHARED_TENANT: osdu
    VENDOR: anthos
  script:
    - $MAVEN_BUILD . test-results.log verify -q -f $CORE_TEST_SUBDIR/pom.xml

core-containerize-bootstrap-gitlab:
  variables:
    IMAGE_BOOTSTRAP_NAME: "core-plus-bootstrap-schema"
  tags: ["osdu-medium"]
