variables:
  CIMPL_SERVICE: schema
  CIMPL_BUILD_BOOTSTRAP_PATH: "devops/core-plus/bootstrap-osdu-module/Dockerfile"
  CIMPL_BUILD_PATH: "schema-core-plus/cloudbuild/Dockerfile"
  CIMPL_HELM_PACKAGE_NAME: core-plus-schema-deploy
  CIMPL_ENABLE_BOOTSTRAP: "true"
  CIMPL_HELM_TIMEOUT: "--timeout 15m"

cimpl-containerize-bootstrap-gitlab:
  tags: ["osdu-medium"]
  variables:
    CIMPL_IMAGE_BOOTSTRAP_NAME: "core-plus-bootstrap-schema"

cimpl-acceptance-test:
  variables:
    ROOT_USER_OPENID_PROVIDER_CLIENT_ID: $PRIVILEGED_USER_OPENID_PROVIDER_CLIENT_ID
    ROOT_USER_OPENID_PROVIDER_CLIENT_SECRET: $PRIVILEGED_USER_OPENID_PROVIDER_CLIENT_SECRET
  
#dev2 jobs

cimpl-dev2-acceptance-test:
  variables:
    ROOT_USER_OPENID_PROVIDER_CLIENT_ID: $PRIVILEGED_USER_OPENID_PROVIDER_CLIENT_ID
    ROOT_USER_OPENID_PROVIDER_CLIENT_SECRET: $PRIVILEGED_USER_OPENID_PROVIDER_CLIENT_SECRET