apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  SHARED_TENANT_NAME: {{- if not .Values.global.onPremEnabled }}
    {{ "system" }}
  {{- else }}
    {{ .Values.global.dataPartitionId | quote }}
  {{- end }}
  LOG_LEVEL: {{ .Values.data.logLevel | default .Values.global.logLevel | quote }}
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  SCHEMA_CHANGED_TOPIC_NAME: {{ .Values.data.schemaTopicName | quote }}
  SCHEMA_CHANGED_MESSAGING_ENABLED: {{ .Values.data.schemaChangedMessagingEnabled | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  {{- if .Values.global.onPremEnabled }}
  SPRING_PROFILES_ACTIVE: "anthos"
  {{- else }}
  SPRING_PROFILES_ACTIVE: "gcp"
  {{- end }}
  _JAVA_OPTIONS: {{ .Values.data.javaOptions | quote }}
