schemaVersion: 3
service:
  name: schema
  archetype: java-maven-azure
tests:
  acceptance:
    type: maven
    path: schema-acceptance-test
    mavenArguments: [verify]
    timeoutMinutes: 20
    bindings:
      HOST: { source: gateway }
      DATA_PARTITION_ID: { source: partition }
      SHARED_TENANT: { source: static, value: osdu }
      PRIVILEGED_USER_TOKEN: { source: token }
  integration:
    type: maven
    path: testing
    mavenArguments: [-pl, schema-test-azure, -am, verify]
    timeoutMinutes: 20
    bindings:
      VENDOR: { source: static, value: azure }
      HOST: { source: gateway }
      PRIVATE_TENANT1: { source: partition }
      PRIVATE_TENANT2: { source: partition }
      SHARED_TENANT: { source: static, value: osdu }
      INTEGRATION_TESTER_ACCESS_TOKEN: { source: token }
