apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  GCP_SCHEMA_CHANGED_TOPIC_NAME: {{ .Values.data.schemaTopicName | quote }}
  GCP_SCHEMA_CHANGED_MESSAGING_ENABLED: {{ .Values.data.schemaChangedMessagingEnabled | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  SHARED_TENANT_NAME: {{ .Values.data.dataPartitionId | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  _JAVA_OPTIONS: {{ .Values.data.javaOptions | quote }}
